### ISSUE TITLE
Understanding the training procedure

### ISSUE THREAD

**Issue by tugcekiziltepe** [zhoubenjia/GFSLT-VLP#12]
I want to apply the VLP technique by trying different encoder and decoder architectures. But I had some difficulty understanding the code and the article. In this case, should I first update and run train_vlp_v2.py, and then update and run train_slt.py according to my own model?

**Comment by zhoubenjia** [comment]
Yes, you're correct. Our model undergoes training in two distinct stages: alignment, which involves executing either train_vlp.py or train_vlp_v2.py, followed by translation, carried out by running train_slt.py.

**Comment by zhoubenjia** [comment]
> I want to apply the VLP technique by trying different encoder and decoder architectures. But I had some difficulty understanding the code and the article. In this case, should I first update and run train_vlp_v2.py, and then update and run train_slt.py according to my own model?

Yes, you're correct. Our model undergoes training in two distinct stages: alignment, which involves executing either train_vlp.py or train_vlp_v2.py, followed by translation, carried out by running train_slt.py.
