### ISSUE TITLE
TextClip model embedding

### ISSUE THREAD

**Issue by chau25102001** [zhoubenjia/GFSLT-VLP#15]
Hi, thank you for your great work

I have a question regarding this line of code in your ```models.py``` file:
https://github.com/zhoubenjia/GFSLT-VLP/blob/91ba953cf26492cd085fc12d20dc952f2a727ee1/models.py#L148

If I understand correctly, this is to get the embedding of one token in the input sequence as the whole sentence embedding. Normally, one would use the 'cls' token or the 'eos' token embedding for sentence embedding. But here I see you are using the embedding of token with maximum token id value in the sentence: ```x['input_ids'].argmax(dim=-1)```. BartTokenizer defines 'cls' token id as 0 and 'eos' token id as 2 and they are clearly not the maximum token id value in a sentence. So why are you using argmax here instead of using 'cls' or 'eos' token embedding?

Thanks in advance

**Comment by zhoubenjia** [comment]
> Hi, thank you for your great work
> 
> I have a question regarding this line of code in your `models.py` file:
> 
> https://github.com/zhoubenjia/GFSLT-VLP/blob/91ba953cf26492cd085fc12d20dc952f2a727ee1/models.py#L148
> 
> If I understand correctly, this is to get the embedding of one token in the input sequence as the whole sentence embedding. Normally, one would use the 'cls' token or the 'eos' token embedding for sentence embedding. But here I see you are using the embedding of token with maximum token id value in the sentence: `x['input_ids'].argmax(dim=-1)`. BartTokenizer defines 'cls' token id as 0 and 'eos' token id as 2 and they are clearly not the maximum token id value in a sentence. So why are you using argmax here instead of using 'cls' or 'eos' token embedding?
> 
> Thanks in advance

Hi, we utilize [MBartTokenizer](https://huggingface.co/docs/transformers/model_doc/mbart).

**Comment by chau25102001** [comment]
> > Hi, thank you for your great work
> > I have a question regarding this line of code in your `models.py` file:
> > https://github.com/zhoubenjia/GFSLT-VLP/blob/91ba953cf26492cd085fc12d20dc952f2a727ee1/models.py#L148
> > 
> > If I understand correctly, this is to get the embedding of one token in the input sequence as the whole sentence embedding. Normally, one would use the 'cls' token or the 'eos' token embedding for sentence embedding. But here I see you are using the embedding of token with maximum token id value in the sentence: `x['input_ids'].argmax(dim=-1)`. BartTokenizer defines 'cls' token id as 0 and 'eos' token id as 2 and they are clearly not the maximum token id value in a sentence. So why are you using argmax here instead of using 'cls' or 'eos' token embedding?
> > Thanks in advance
> 
> Hi, we utilize [MBartTokenizer](https://huggingface.co/docs/transformers/model_doc/mbart).

I tried print out the input_ids, apparently the eos token id is set to be the length of the vocab size, hence making it always the one with the highest value in the input_ids. The use of "argmax" makes sense here. Thanks
