### ISSUE TITLE
Download Links for the pre-processed model

### ISSUE THREAD

**Issue by peonycabbage** [zhoubenjia/GFSLT-VLP#17]
I wanted to inquire if there is an alternative location where I can download the pre-processed model, as I am experiencing some difficulties accessing the Baidu disk option from outside of China.
Thank you very much.

**Comment by zhoubenjia** [comment]
> I wanted to inquire if there is an alternative location where I can download the pre-processed model, as I am experiencing some difficulties accessing the Baidu disk option from outside of China. Thank you very much.

Please prepare the pre-trained model as follows:
- Download mbart model from [🤗huggingface](https://huggingface.co/docs/transformers/main/en/model_doc/mbart).
- Use [hf-trim](https://github.com/IamAdiSri/hf-trim?tab=readme-ov-file) to reduce the size of [🤗huggingface models ](https://huggingface.co/docs/transformers/main/en/model_doc/mbart) via vocabulary trimming.
You can also refer to the [README](https://github.com/zhoubenjia/GFSLT-VLP/tree/main/pretrain_models#readme) for more detail.

**Comment by peonycabbage** [comment]
Thank you very much for the guidance.

**Comment by peonycabbage** [comment]
Hi,  I am able to generate all files except pytorch_model.bin 
I'd like to kindly ask if you have any instructions for generating this file.

Also, if the pre-trained models are available for download in either google drive or one drive, we would be very grateful.

Thank you once again.
