### ISSUE TITLE
About the use of gloss

### ISSUE THREAD

**Issue by peonycabbage** [zhoubenjia/GFSLT-VLP#18]
Hello,

Thank you for sharing your code. I am wondering where the gloss labels fit into the architecture. Was it used for pre-training or other tasks?

Thank you

**Comment by zhoubenjia** [comment]
> Hello,
> 
> Thank you for sharing your code. I am wondering where the gloss labels fit into the architecture. Was it used for pre-training or other tasks?
> 
> Thank you

Hi, thank you for your attention to our work. This work does not require gloss annotation because it is a gloss-free SLT architecture.

**Comment by peonycabbage** [comment]
Thank you very much for the reply.
