### ISSUE TITLE
Checkpoint Load Error. torch.load results in _pickle.UnpicklingError: state is not a dictionary

### ISSUE THREAD

**Issue by abcqmars** [zhoubenjia/GFSLT-VLP#3]
`state_dict = torch.load(model_path, map_location='cpu')`
When the model_path is the path of best_checkpoint.pth, Raising Error: _pickle.UnpicklingError: state is not a dictionary.
While It works for loading normal checkpoint.pth.

Such bug preventing finetuning from using best checkpoint.

**Comment by zhoubenjia** [comment]
> `state_dict = torch.load(model_path, map_location='cpu')` When the model_path is the path of best_checkpoint.pth, Raising Error: _pickle.UnpicklingError: state is not a dictionary. While It works for loading normal checkpoint.pth.
> 
> Such bug preventing finetuning from using best checkpoint.

We are very grateful to you for pointing out this issue and deeply sorry for the bug in our code. We will fix it as soon as possible. Please continue to pay attention.

**Comment by zhoubenjia** [comment]
The BUG has been fixed. Thank you again for your attention to our work.
