### ISSUE TITLE
How many GPUs are required for this task?

### ISSUE THREAD

**Issue by xxxiaosong** [zhoubenjia/GFSLT-VLP#6]
How many GPUs are required for this task?

**Comment by zhoubenjia** [comment]
> How many GPUs are required for this task?

Thank you very much for your attention to our work. In our experimental setup, we harnessed the computational power of 4 Nvidia RTX 3090 GPUs. In theory, a greater number of GPUs can be advantageous, as our approach relies on a symmetric cross-entropy loss, akin to the one used in CLIP. The increased computational resources can potentially enhance the model's performance further.

**Comment by xxxiaosong** [comment]
Thanks for your reply! And how much time does the training process consume for each dataset....

**Comment by zhoubenjia** [comment]
> Thanks for your reply! And how much time does the training process consume for each dataset....

Phase 1 (80 epoch) lasts about 24 hours, phase 2 (200 epoch) lasts about 36 hours. Hope this helps.

**Comment by xxxiaosong** [comment]
Thks, this helps a lot!

**Comment by rabeya-akter** [comment]
Can you give information about the model parameter number and inference time?
