### ISSUE TITLE
config of CSL-Daily

### ISSUE THREAD

**Issue by ZechengLi19** [zhoubenjia/GFSLT-VLP#7]
Thanks for your awesome work! I don’t find the config file corresponding to CSL-Daily. Could you provide it?

**Comment by Kakarot1103** [comment]
> I use the **hf-trim** method mentioned by the author on the **Phonexi-2014T** dataset, but in the second step, my dictionary size is 2215, not the provided 2454. At the same time, I am also curious about how to obtain pytorch_pretrain.bin in the third step. Could you provide a code? Thank you so much!

1. The model with a size of 2454 was created in our early experiments about gloss-to-text translation.  It has little effect because the extra word embedding doesn't get trained in gloss-free experiments.  2. You can find the code in trim_model.py.

**Comment by Kakarot1103** [comment]
> Also, I'm curious, how to use trim pruning to the model? Could you provide a code? Thank you so much!

You can find code in trim_model.py

**Comment by Kakarot1103** [comment]
> Thanks for your awesome work! I don’t find the config file corresponding to CSL-Daily. Could you provide it?

We use char-based tokenizer in the CSL-Daily experiment so the code will be a little different. We will update soon.

**Comment by ZechengLi19** [comment]
> > Thanks for your awesome work! I don’t find the config file corresponding to CSL-Daily. Could you provide it?
> 
> We use char-based tokenizer in the CSL-Daily experiment so the code will be a little different. We will update soon.

Looking forward to your updates~

**Comment by ZechengLi19** [comment]
@Kakarot1103 
Sorry to bother you, I'm curious, for the csl-daily dataset, when I calculate performance such as bleu, do I need to use spaces to separate each char? 

I changed line442 in the evaluate function to migrate it to the Chinese domain. https://github.com/zhoubenjia/GFSLT-VLP/blob/4699132e1f71ee259133fb05f4373794fc4f94a2/train_slt.py#L442
```  
    tgt_pres = tokenizer.batch_decode(tgt_pres, skip_special_tokens=True)
    tgt_refs = tokenizer.batch_decode(tgt_refs, skip_special_tokens=True)
    tgt_pres = [' '.join(list(r)) for r in tgt_pres]
    tgt_refs = [' '.join(list(r)) for r in tgt_refs]
```

Is this the right approach? Or do I need to do something else?

**Comment by Kakarot1103** [comment]
This is a question worth discussing. The output of tokenizer.batch_decode is a continuous Chinese sentence like "我去吃饭了“. When you calculate the bleu score, you can use either the char-based method like "我 去 吃 饭 了“ or the word-based method like "我 去 吃饭 了". Typically, the former method will have a higher bleu score than the latter. In our experiments, we used a char-based approach for performance evaluation just like previous work ( [1],[2]). Your code is correct.

[1] Hao Zhou, Wengang Zhou, Weizhen Qi, Junfu Pu, and Houqiang Li, "Improving Sign Language Translation with Monolingual Data by Sign Back-Translation," IEEE/CVF International Conference on Computer Vision and Pattern Recognition (CVPR), 2021.
[2] Chen, Yutong and Wei, Fangyun and Sun, Xiao and Wu, Zhirong and Lin, Stephen, "A Simple Multi-Modality Transfer Learning Baseline for Sign Language Translation," Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2022.

**Comment by Kakarot1103** [comment]
> @Kakarot1103 Sorry to bother you, I'm curious, for the csl-daily dataset, when I calculate performance such as bleu, do I need to use spaces to separate each char?
> 
> I changed line442 in the evaluate function to migrate it to the Chinese domain.
> 
> https://github.com/zhoubenjia/GFSLT-VLP/blob/4699132e1f71ee259133fb05f4373794fc4f94a2/train_slt.py#L442
> 
> ```
>     tgt_pres = tokenizer.batch_decode(tgt_pres, skip_special_tokens=True)
>     tgt_refs = tokenizer.batch_decode(tgt_refs, skip_special_tokens=True)
>     tgt_pres = [' '.join(list(r)) for r in tgt_pres]
>     tgt_refs = [' '.join(list(r)) for r in tgt_refs]
> ```
> 
> Is this the right approach? Or do I need to do something else?

This is a question worth discussing. The output of tokenizer.batch_decode is a continuous Chinese sentence like "我去吃饭了“. When you calculate the bleu score, you can use either the char-based method like "我 去 吃 饭 了“ or the word-based method like "我 去 吃饭 了". Typically, the former method will have a higher bleu score than the latter. In our experiments, we used a char-based approach for performance evaluation just like previous work ( [1],[2]). Your code is correct.

[1] Hao Zhou, Wengang Zhou, Weizhen Qi, Junfu Pu, and Houqiang Li, "Improving Sign Language Translation with Monolingual Data by Sign Back-Translation," IEEE/CVF International Conference on Computer Vision and Pattern Recognition (CVPR), 2021.
[2] Chen, Yutong and Wei, Fangyun and Sun, Xiao and Wu, Zhirong and Lin, Stephen, "A Simple Multi-Modality Transfer Learning Baseline for Sign Language Translation," Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2022.

**Comment by ZechengLi19** [comment]
> > @Kakarot1103 Sorry to bother you, I'm curious, for the csl-daily dataset, when I calculate performance such as bleu, do I need to use spaces to separate each char?
> > I changed line442 in the evaluate function to migrate it to the Chinese domain.
> > https://github.com/zhoubenjia/GFSLT-VLP/blob/4699132e1f71ee259133fb05f4373794fc4f94a2/train_slt.py#L442
> > 
> > ```
> >     tgt_pres = tokenizer.batch_decode(tgt_pres, skip_special_tokens=True)
> >     tgt_refs = tokenizer.batch_decode(tgt_refs, skip_special_tokens=True)
> >     tgt_pres = [' '.join(list(r)) for r in tgt_pres]
> >     tgt_refs = [' '.join(list(r)) for r in tgt_refs]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is this the right approach? Or do I need to do something else?
> 
> This is a question worth discussing. The output of tokenizer.batch_decode is a continuous Chinese sentence like "我去吃饭了“. When you calculate the bleu score, you can use either the char-based method like "我 去 吃 饭 了“ or the word-based method like "我 去 吃饭 了". Typically, the former method will have a higher bleu score than the latter. In our experiments, we used a char-based approach for performance evaluation just like previous work ( [1],[2]). Your code is correct.
> 
> [1] Hao Zhou, Wengang Zhou, Weizhen Qi, Junfu Pu, and Houqiang Li, "Improving Sign Language Translation with Monolingual Data by Sign Back-Translation," IEEE/CVF International Conference on Computer Vision and Pattern Recognition (CVPR), 2021. [2] Chen, Yutong and Wei, Fangyun and Sun, Xiao and Wu, Zhirong and Lin, Stephen, "A Simple Multi-Modality Transfer Learning Baseline for Sign Language Translation," Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2022.

Get! Thanks for your reply!
